dist: ncmc
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=ncmc

matrix:
  include:
    # Linux
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

      # Windows
    - env: TARGET=x86_64-pc-windows-gnu

    # Testing other channels
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: con7EZvpUFx13lnc6kbunyz+iSDa+X/hjvP5tjkaxh2KQaye4CA/ffx8p+2ewRCcAEWcA4Cp3KC2SgSVeYw9KiJ3bq4ukJR2kpYCRqTkhHNTJSnP4RcAkQ6gNNIbTVGuWDBwTwTy6EnJeubvTXFPrYTj6zT28Ppm72xUmZAqpWg1BRrBn9E+A+wQip/Qcu3APxqGX0lq4I0nuFRrz4YzJEi6gpR8yDANwO5zr3tEzFHAMluGeDs91K3kp2aie8P9WIMRwwiNDwh2vf35+n3BGf9EpBH5InxUcExz8gdou1Pxlc0DxU1u0SfKVlvz1gwShJ0eQpuYjpXmeFN1JboHIuMdjJDW2TXs4sV5dEGsyqBLB8Lvcu3aMM8IbWqhv/FiaDAfxI6BnRQIfNrjt4xZscGL8k3y4w+hSSK2jM0nYcdW9e4t/eMJITcvo3El1NShJouv+pw2kNbXiGbldQIxrxtrtTO2o0+5xtG1GQcI+Zz/mzsFcRFSwo5cKePYFZomgnr0uUqxx/y1nPQq10NXCMNU4S6QwApjWGtSwOFvUgsd4E+fhV+RKvs/o04P3iwUHIJ8b8iz88uvIFNeABY4VAeyl1B0Ksdepb6iMMn/toCUuVpBSEGTJE53EvpTbeMMdGLVeR/hrjCU9/9CIViRJ6fFuLnKzfLUzG8rie0XiTY=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  skip_cleanup: true

before_cache:
  - chmod -R a+r $HOME/.cargo

cache: cargo

branches:
  only:
    # release tags
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
    - master

notifications:
  email:
    on_success: never
