[package]
name = "ncmc"
version = "0.1.2"
authors = ["阿卡琳 <hufan.akarin@Gmail.com>"]

description = "convert encrypted ncm file to original music file."
homepage = "https://github.com/hufan-akari/ncmc"
repository = "https://github.com/hufan-akari/ncmc"
license = "MIT"
readme = "README.md"
keywords = ["ncm", "converter", "ncmdump"]

[badges]
travis-ci = { repository = "hufan-akari/ncmc" }
appveyor = { repository = "hufan-akari/ncmc" }

[dependencies]
aes = "0.2.0"
block-modes = "0.1.0"
base64 = "0.9.2"
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.26"
glob = "0.2.11"
metaflac = "0.1.8"
id3 = "0.2.4"

[profile.release]
panic = "abort"
lto = true
