[package]
name = "ncmc"
version = "0.1.1"
authors = ["阿卡琳 <hufan.akarin@Gmail.com>"]

[dependencies]
aes = "0.2.0"
block-modes = "0.1.0"
base64 = "0.9.2"
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.26"
glob = "0.2.11"
metaflac = "0.1.8"
id3 = "0.2.4"

[profile.release]
lto = true
